// Code generated by protoc-gen-go. DO NOT EDIT.
// source: esterpad.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SMessages struct {
	Sm                   []*SMessage `protobuf:"bytes,1,rep,name=sm,proto3" json:"sm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SMessages) Reset()         { *m = SMessages{} }
func (m *SMessages) String() string { return proto.CompactTextString(m) }
func (*SMessages) ProtoMessage()    {}
func (*SMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{0}
}

func (m *SMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMessages.Unmarshal(m, b)
}
func (m *SMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMessages.Marshal(b, m, deterministic)
}
func (m *SMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMessages.Merge(m, src)
}
func (m *SMessages) XXX_Size() int {
	return xxx_messageInfo_SMessages.Size(m)
}
func (m *SMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_SMessages.DiscardUnknown(m)
}

var xxx_messageInfo_SMessages proto.InternalMessageInfo

func (m *SMessages) GetSm() []*SMessage {
	if m != nil {
		return m.Sm
	}
	return nil
}

type SMessage struct {
	// Types that are valid to be assigned to SMessage:
	//	*SMessage_Chat
	//	*SMessage_Delta
	//	*SMessage_DeltaDropped
	//	*SMessage_Document
	//	*SMessage_Auth
	//	*SMessage_AuthError
	//	*SMessage_UserLeave
	//	*SMessage_UserInfo
	//	*SMessage_PadList
	SMessage             isSMessage_SMessage `protobuf_oneof:"SMessage"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SMessage) Reset()         { *m = SMessage{} }
func (m *SMessage) String() string { return proto.CompactTextString(m) }
func (*SMessage) ProtoMessage()    {}
func (*SMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{1}
}

func (m *SMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMessage.Unmarshal(m, b)
}
func (m *SMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMessage.Marshal(b, m, deterministic)
}
func (m *SMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMessage.Merge(m, src)
}
func (m *SMessage) XXX_Size() int {
	return xxx_messageInfo_SMessage.Size(m)
}
func (m *SMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SMessage proto.InternalMessageInfo

type isSMessage_SMessage interface {
	isSMessage_SMessage()
}

type SMessage_Chat struct {
	Chat *SChat `protobuf:"bytes,1,opt,name=Chat,proto3,oneof"`
}

type SMessage_Delta struct {
	Delta *SDelta `protobuf:"bytes,2,opt,name=Delta,proto3,oneof"`
}

type SMessage_DeltaDropped struct {
	DeltaDropped *SDeltaDropped `protobuf:"bytes,3,opt,name=DeltaDropped,proto3,oneof"`
}

type SMessage_Document struct {
	Document *SDocument `protobuf:"bytes,4,opt,name=Document,proto3,oneof"`
}

type SMessage_Auth struct {
	Auth *SAuth `protobuf:"bytes,5,opt,name=Auth,proto3,oneof"`
}

type SMessage_AuthError struct {
	AuthError *SAuthError `protobuf:"bytes,6,opt,name=AuthError,proto3,oneof"`
}

type SMessage_UserLeave struct {
	UserLeave *SUserLeave `protobuf:"bytes,7,opt,name=UserLeave,proto3,oneof"`
}

type SMessage_UserInfo struct {
	UserInfo *SUserInfo `protobuf:"bytes,8,opt,name=UserInfo,proto3,oneof"`
}

type SMessage_PadList struct {
	PadList *SPadList `protobuf:"bytes,9,opt,name=PadList,proto3,oneof"`
}

func (*SMessage_Chat) isSMessage_SMessage() {}

func (*SMessage_Delta) isSMessage_SMessage() {}

func (*SMessage_DeltaDropped) isSMessage_SMessage() {}

func (*SMessage_Document) isSMessage_SMessage() {}

func (*SMessage_Auth) isSMessage_SMessage() {}

func (*SMessage_AuthError) isSMessage_SMessage() {}

func (*SMessage_UserLeave) isSMessage_SMessage() {}

func (*SMessage_UserInfo) isSMessage_SMessage() {}

func (*SMessage_PadList) isSMessage_SMessage() {}

func (m *SMessage) GetSMessage() isSMessage_SMessage {
	if m != nil {
		return m.SMessage
	}
	return nil
}

func (m *SMessage) GetChat() *SChat {
	if x, ok := m.GetSMessage().(*SMessage_Chat); ok {
		return x.Chat
	}
	return nil
}

func (m *SMessage) GetDelta() *SDelta {
	if x, ok := m.GetSMessage().(*SMessage_Delta); ok {
		return x.Delta
	}
	return nil
}

func (m *SMessage) GetDeltaDropped() *SDeltaDropped {
	if x, ok := m.GetSMessage().(*SMessage_DeltaDropped); ok {
		return x.DeltaDropped
	}
	return nil
}

func (m *SMessage) GetDocument() *SDocument {
	if x, ok := m.GetSMessage().(*SMessage_Document); ok {
		return x.Document
	}
	return nil
}

func (m *SMessage) GetAuth() *SAuth {
	if x, ok := m.GetSMessage().(*SMessage_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *SMessage) GetAuthError() *SAuthError {
	if x, ok := m.GetSMessage().(*SMessage_AuthError); ok {
		return x.AuthError
	}
	return nil
}

func (m *SMessage) GetUserLeave() *SUserLeave {
	if x, ok := m.GetSMessage().(*SMessage_UserLeave); ok {
		return x.UserLeave
	}
	return nil
}

func (m *SMessage) GetUserInfo() *SUserInfo {
	if x, ok := m.GetSMessage().(*SMessage_UserInfo); ok {
		return x.UserInfo
	}
	return nil
}

func (m *SMessage) GetPadList() *SPadList {
	if x, ok := m.GetSMessage().(*SMessage_PadList); ok {
		return x.PadList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SMessage_Chat)(nil),
		(*SMessage_Delta)(nil),
		(*SMessage_DeltaDropped)(nil),
		(*SMessage_Document)(nil),
		(*SMessage_Auth)(nil),
		(*SMessage_AuthError)(nil),
		(*SMessage_UserLeave)(nil),
		(*SMessage_UserInfo)(nil),
		(*SMessage_PadList)(nil),
	}
}

type SChat struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SChat) Reset()         { *m = SChat{} }
func (m *SChat) String() string { return proto.CompactTextString(m) }
func (*SChat) ProtoMessage()    {}
func (*SChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{2}
}

func (m *SChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SChat.Unmarshal(m, b)
}
func (m *SChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SChat.Marshal(b, m, deterministic)
}
func (m *SChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SChat.Merge(m, src)
}
func (m *SChat) XXX_Size() int {
	return xxx_messageInfo_SChat.Size(m)
}
func (m *SChat) XXX_DiscardUnknown() {
	xxx_messageInfo_SChat.DiscardUnknown(m)
}

var xxx_messageInfo_SChat proto.InternalMessageInfo

func (m *SChat) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SChat) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SChat) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SDelta struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Ops                  []*Op    `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDelta) Reset()         { *m = SDelta{} }
func (m *SDelta) String() string { return proto.CompactTextString(m) }
func (*SDelta) ProtoMessage()    {}
func (*SDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{3}
}

func (m *SDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDelta.Unmarshal(m, b)
}
func (m *SDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDelta.Marshal(b, m, deterministic)
}
func (m *SDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDelta.Merge(m, src)
}
func (m *SDelta) XXX_Size() int {
	return xxx_messageInfo_SDelta.Size(m)
}
func (m *SDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_SDelta.DiscardUnknown(m)
}

var xxx_messageInfo_SDelta proto.InternalMessageInfo

func (m *SDelta) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SDelta) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SDelta) GetOps() []*Op {
	if m != nil {
		return m.Ops
	}
	return nil
}

type SDeltaDropped struct {
	Revision             uint32   `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDeltaDropped) Reset()         { *m = SDeltaDropped{} }
func (m *SDeltaDropped) String() string { return proto.CompactTextString(m) }
func (*SDeltaDropped) ProtoMessage()    {}
func (*SDeltaDropped) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{4}
}

func (m *SDeltaDropped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDeltaDropped.Unmarshal(m, b)
}
func (m *SDeltaDropped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDeltaDropped.Marshal(b, m, deterministic)
}
func (m *SDeltaDropped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDeltaDropped.Merge(m, src)
}
func (m *SDeltaDropped) XXX_Size() int {
	return xxx_messageInfo_SDeltaDropped.Size(m)
}
func (m *SDeltaDropped) XXX_DiscardUnknown() {
	xxx_messageInfo_SDeltaDropped.DiscardUnknown(m)
}

var xxx_messageInfo_SDeltaDropped proto.InternalMessageInfo

func (m *SDeltaDropped) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

type SDocument struct {
	Revision             uint32   `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Ops                  []*Op    `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDocument) Reset()         { *m = SDocument{} }
func (m *SDocument) String() string { return proto.CompactTextString(m) }
func (*SDocument) ProtoMessage()    {}
func (*SDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{5}
}

func (m *SDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDocument.Unmarshal(m, b)
}
func (m *SDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDocument.Marshal(b, m, deterministic)
}
func (m *SDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDocument.Merge(m, src)
}
func (m *SDocument) XXX_Size() int {
	return xxx_messageInfo_SDocument.Size(m)
}
func (m *SDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_SDocument.DiscardUnknown(m)
}

var xxx_messageInfo_SDocument proto.InternalMessageInfo

func (m *SDocument) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *SDocument) GetOps() []*Op {
	if m != nil {
		return m.Ops
	}
	return nil
}

type SAuth struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color                uint32   `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Perms                uint32   `protobuf:"varint,4,opt,name=perms,proto3" json:"perms,omitempty"`
	SessId               string   `protobuf:"bytes,5,opt,name=sessId,proto3" json:"sessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SAuth) Reset()         { *m = SAuth{} }
func (m *SAuth) String() string { return proto.CompactTextString(m) }
func (*SAuth) ProtoMessage()    {}
func (*SAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{6}
}

func (m *SAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SAuth.Unmarshal(m, b)
}
func (m *SAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SAuth.Marshal(b, m, deterministic)
}
func (m *SAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SAuth.Merge(m, src)
}
func (m *SAuth) XXX_Size() int {
	return xxx_messageInfo_SAuth.Size(m)
}
func (m *SAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_SAuth.DiscardUnknown(m)
}

var xxx_messageInfo_SAuth proto.InternalMessageInfo

func (m *SAuth) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SAuth) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SAuth) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *SAuth) GetPerms() uint32 {
	if m != nil {
		return m.Perms
	}
	return 0
}

func (m *SAuth) GetSessId() string {
	if m != nil {
		return m.SessId
	}
	return ""
}

type SAuthError struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SAuthError) Reset()         { *m = SAuthError{} }
func (m *SAuthError) String() string { return proto.CompactTextString(m) }
func (*SAuthError) ProtoMessage()    {}
func (*SAuthError) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{7}
}

func (m *SAuthError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SAuthError.Unmarshal(m, b)
}
func (m *SAuthError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SAuthError.Marshal(b, m, deterministic)
}
func (m *SAuthError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SAuthError.Merge(m, src)
}
func (m *SAuthError) XXX_Size() int {
	return xxx_messageInfo_SAuthError.Size(m)
}
func (m *SAuthError) XXX_DiscardUnknown() {
	xxx_messageInfo_SAuthError.DiscardUnknown(m)
}

var xxx_messageInfo_SAuthError proto.InternalMessageInfo

func (m *SAuthError) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type SUserLeave struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SUserLeave) Reset()         { *m = SUserLeave{} }
func (m *SUserLeave) String() string { return proto.CompactTextString(m) }
func (*SUserLeave) ProtoMessage()    {}
func (*SUserLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{8}
}

func (m *SUserLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SUserLeave.Unmarshal(m, b)
}
func (m *SUserLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SUserLeave.Marshal(b, m, deterministic)
}
func (m *SUserLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SUserLeave.Merge(m, src)
}
func (m *SUserLeave) XXX_Size() int {
	return xxx_messageInfo_SUserLeave.Size(m)
}
func (m *SUserLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_SUserLeave.DiscardUnknown(m)
}

var xxx_messageInfo_SUserLeave proto.InternalMessageInfo

func (m *SUserLeave) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SUserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color                uint32   `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Perms                uint32   `protobuf:"varint,4,opt,name=perms,proto3" json:"perms,omitempty"`
	Online               bool     `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	Ip                   string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent            string   `protobuf:"bytes,7,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SUserInfo) Reset()         { *m = SUserInfo{} }
func (m *SUserInfo) String() string { return proto.CompactTextString(m) }
func (*SUserInfo) ProtoMessage()    {}
func (*SUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{9}
}

func (m *SUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SUserInfo.Unmarshal(m, b)
}
func (m *SUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SUserInfo.Marshal(b, m, deterministic)
}
func (m *SUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SUserInfo.Merge(m, src)
}
func (m *SUserInfo) XXX_Size() int {
	return xxx_messageInfo_SUserInfo.Size(m)
}
func (m *SUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SUserInfo proto.InternalMessageInfo

func (m *SUserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SUserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SUserInfo) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *SUserInfo) GetPerms() uint32 {
	if m != nil {
		return m.Perms
	}
	return 0
}

func (m *SUserInfo) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *SUserInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SUserInfo) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

type SPadList struct {
	Pads                 []string `protobuf:"bytes,1,rep,name=pads,proto3" json:"pads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SPadList) Reset()         { *m = SPadList{} }
func (m *SPadList) String() string { return proto.CompactTextString(m) }
func (*SPadList) ProtoMessage()    {}
func (*SPadList) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{10}
}

func (m *SPadList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPadList.Unmarshal(m, b)
}
func (m *SPadList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPadList.Marshal(b, m, deterministic)
}
func (m *SPadList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPadList.Merge(m, src)
}
func (m *SPadList) XXX_Size() int {
	return xxx_messageInfo_SPadList.Size(m)
}
func (m *SPadList) XXX_DiscardUnknown() {
	xxx_messageInfo_SPadList.DiscardUnknown(m)
}

var xxx_messageInfo_SPadList proto.InternalMessageInfo

func (m *SPadList) GetPads() []string {
	if m != nil {
		return m.Pads
	}
	return nil
}

type CMessages struct {
	Cm                   []*CMessage `protobuf:"bytes,1,rep,name=cm,proto3" json:"cm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CMessages) Reset()         { *m = CMessages{} }
func (m *CMessages) String() string { return proto.CompactTextString(m) }
func (*CMessages) ProtoMessage()    {}
func (*CMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{11}
}

func (m *CMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMessages.Unmarshal(m, b)
}
func (m *CMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMessages.Marshal(b, m, deterministic)
}
func (m *CMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMessages.Merge(m, src)
}
func (m *CMessages) XXX_Size() int {
	return xxx_messageInfo_CMessages.Size(m)
}
func (m *CMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_CMessages.DiscardUnknown(m)
}

var xxx_messageInfo_CMessages proto.InternalMessageInfo

func (m *CMessages) GetCm() []*CMessage {
	if m != nil {
		return m.Cm
	}
	return nil
}

type CMessage struct {
	// Types that are valid to be assigned to CMessage:
	//	*CMessage_EditUser
	//	*CMessage_Delta
	//	*CMessage_Chat
	//	*CMessage_Session
	//	*CMessage_Login
	//	*CMessage_Logout
	//	*CMessage_Register
	//	*CMessage_GuestLogin
	//	*CMessage_EnterPad
	//	*CMessage_LeavePad
	//	*CMessage_AdminUser
	//	*CMessage_ChatRequest
	//	*CMessage_RevisionRequest
	//	*CMessage_InvertDelta
	//	*CMessage_InvertUserDelta
	//	*CMessage_RestoreRevision
	CMessage             isCMessage_CMessage `protobuf_oneof:"CMessage"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CMessage) Reset()         { *m = CMessage{} }
func (m *CMessage) String() string { return proto.CompactTextString(m) }
func (*CMessage) ProtoMessage()    {}
func (*CMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{12}
}

func (m *CMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMessage.Unmarshal(m, b)
}
func (m *CMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMessage.Marshal(b, m, deterministic)
}
func (m *CMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMessage.Merge(m, src)
}
func (m *CMessage) XXX_Size() int {
	return xxx_messageInfo_CMessage.Size(m)
}
func (m *CMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CMessage proto.InternalMessageInfo

type isCMessage_CMessage interface {
	isCMessage_CMessage()
}

type CMessage_EditUser struct {
	EditUser *CEditUser `protobuf:"bytes,1,opt,name=EditUser,proto3,oneof"`
}

type CMessage_Delta struct {
	Delta *CDelta `protobuf:"bytes,2,opt,name=Delta,proto3,oneof"`
}

type CMessage_Chat struct {
	Chat *CChat `protobuf:"bytes,3,opt,name=Chat,proto3,oneof"`
}

type CMessage_Session struct {
	Session *CSession `protobuf:"bytes,4,opt,name=Session,proto3,oneof"`
}

type CMessage_Login struct {
	Login *CLogin `protobuf:"bytes,5,opt,name=Login,proto3,oneof"`
}

type CMessage_Logout struct {
	Logout *CLogout `protobuf:"bytes,6,opt,name=Logout,proto3,oneof"`
}

type CMessage_Register struct {
	Register *CRegister `protobuf:"bytes,7,opt,name=Register,proto3,oneof"`
}

type CMessage_GuestLogin struct {
	GuestLogin *CGuestLogin `protobuf:"bytes,8,opt,name=GuestLogin,proto3,oneof"`
}

type CMessage_EnterPad struct {
	EnterPad *CEnterPad `protobuf:"bytes,9,opt,name=EnterPad,proto3,oneof"`
}

type CMessage_LeavePad struct {
	LeavePad *CLeavePad `protobuf:"bytes,10,opt,name=LeavePad,proto3,oneof"`
}

type CMessage_AdminUser struct {
	AdminUser *CAdminUser `protobuf:"bytes,11,opt,name=AdminUser,proto3,oneof"`
}

type CMessage_ChatRequest struct {
	ChatRequest *CChatRequest `protobuf:"bytes,12,opt,name=ChatRequest,proto3,oneof"`
}

type CMessage_RevisionRequest struct {
	RevisionRequest *CRevisionRequest `protobuf:"bytes,13,opt,name=RevisionRequest,proto3,oneof"`
}

type CMessage_InvertDelta struct {
	InvertDelta *CInvertDelta `protobuf:"bytes,14,opt,name=InvertDelta,proto3,oneof"`
}

type CMessage_InvertUserDelta struct {
	InvertUserDelta *CInvertUserDelta `protobuf:"bytes,15,opt,name=InvertUserDelta,proto3,oneof"`
}

type CMessage_RestoreRevision struct {
	RestoreRevision *CRestoreRevision `protobuf:"bytes,16,opt,name=RestoreRevision,proto3,oneof"`
}

func (*CMessage_EditUser) isCMessage_CMessage() {}

func (*CMessage_Delta) isCMessage_CMessage() {}

func (*CMessage_Chat) isCMessage_CMessage() {}

func (*CMessage_Session) isCMessage_CMessage() {}

func (*CMessage_Login) isCMessage_CMessage() {}

func (*CMessage_Logout) isCMessage_CMessage() {}

func (*CMessage_Register) isCMessage_CMessage() {}

func (*CMessage_GuestLogin) isCMessage_CMessage() {}

func (*CMessage_EnterPad) isCMessage_CMessage() {}

func (*CMessage_LeavePad) isCMessage_CMessage() {}

func (*CMessage_AdminUser) isCMessage_CMessage() {}

func (*CMessage_ChatRequest) isCMessage_CMessage() {}

func (*CMessage_RevisionRequest) isCMessage_CMessage() {}

func (*CMessage_InvertDelta) isCMessage_CMessage() {}

func (*CMessage_InvertUserDelta) isCMessage_CMessage() {}

func (*CMessage_RestoreRevision) isCMessage_CMessage() {}

func (m *CMessage) GetCMessage() isCMessage_CMessage {
	if m != nil {
		return m.CMessage
	}
	return nil
}

func (m *CMessage) GetEditUser() *CEditUser {
	if x, ok := m.GetCMessage().(*CMessage_EditUser); ok {
		return x.EditUser
	}
	return nil
}

func (m *CMessage) GetDelta() *CDelta {
	if x, ok := m.GetCMessage().(*CMessage_Delta); ok {
		return x.Delta
	}
	return nil
}

func (m *CMessage) GetChat() *CChat {
	if x, ok := m.GetCMessage().(*CMessage_Chat); ok {
		return x.Chat
	}
	return nil
}

func (m *CMessage) GetSession() *CSession {
	if x, ok := m.GetCMessage().(*CMessage_Session); ok {
		return x.Session
	}
	return nil
}

func (m *CMessage) GetLogin() *CLogin {
	if x, ok := m.GetCMessage().(*CMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (m *CMessage) GetLogout() *CLogout {
	if x, ok := m.GetCMessage().(*CMessage_Logout); ok {
		return x.Logout
	}
	return nil
}

func (m *CMessage) GetRegister() *CRegister {
	if x, ok := m.GetCMessage().(*CMessage_Register); ok {
		return x.Register
	}
	return nil
}

func (m *CMessage) GetGuestLogin() *CGuestLogin {
	if x, ok := m.GetCMessage().(*CMessage_GuestLogin); ok {
		return x.GuestLogin
	}
	return nil
}

func (m *CMessage) GetEnterPad() *CEnterPad {
	if x, ok := m.GetCMessage().(*CMessage_EnterPad); ok {
		return x.EnterPad
	}
	return nil
}

func (m *CMessage) GetLeavePad() *CLeavePad {
	if x, ok := m.GetCMessage().(*CMessage_LeavePad); ok {
		return x.LeavePad
	}
	return nil
}

func (m *CMessage) GetAdminUser() *CAdminUser {
	if x, ok := m.GetCMessage().(*CMessage_AdminUser); ok {
		return x.AdminUser
	}
	return nil
}

func (m *CMessage) GetChatRequest() *CChatRequest {
	if x, ok := m.GetCMessage().(*CMessage_ChatRequest); ok {
		return x.ChatRequest
	}
	return nil
}

func (m *CMessage) GetRevisionRequest() *CRevisionRequest {
	if x, ok := m.GetCMessage().(*CMessage_RevisionRequest); ok {
		return x.RevisionRequest
	}
	return nil
}

func (m *CMessage) GetInvertDelta() *CInvertDelta {
	if x, ok := m.GetCMessage().(*CMessage_InvertDelta); ok {
		return x.InvertDelta
	}
	return nil
}

func (m *CMessage) GetInvertUserDelta() *CInvertUserDelta {
	if x, ok := m.GetCMessage().(*CMessage_InvertUserDelta); ok {
		return x.InvertUserDelta
	}
	return nil
}

func (m *CMessage) GetRestoreRevision() *CRestoreRevision {
	if x, ok := m.GetCMessage().(*CMessage_RestoreRevision); ok {
		return x.RestoreRevision
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CMessage_EditUser)(nil),
		(*CMessage_Delta)(nil),
		(*CMessage_Chat)(nil),
		(*CMessage_Session)(nil),
		(*CMessage_Login)(nil),
		(*CMessage_Logout)(nil),
		(*CMessage_Register)(nil),
		(*CMessage_GuestLogin)(nil),
		(*CMessage_EnterPad)(nil),
		(*CMessage_LeavePad)(nil),
		(*CMessage_AdminUser)(nil),
		(*CMessage_ChatRequest)(nil),
		(*CMessage_RevisionRequest)(nil),
		(*CMessage_InvertDelta)(nil),
		(*CMessage_InvertUserDelta)(nil),
		(*CMessage_RestoreRevision)(nil),
	}
}

type CEditUser struct {
	Changemask           uint32   `protobuf:"varint,1,opt,name=changemask,proto3" json:"changemask,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color                uint32   `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CEditUser) Reset()         { *m = CEditUser{} }
func (m *CEditUser) String() string { return proto.CompactTextString(m) }
func (*CEditUser) ProtoMessage()    {}
func (*CEditUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{13}
}

func (m *CEditUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CEditUser.Unmarshal(m, b)
}
func (m *CEditUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CEditUser.Marshal(b, m, deterministic)
}
func (m *CEditUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CEditUser.Merge(m, src)
}
func (m *CEditUser) XXX_Size() int {
	return xxx_messageInfo_CEditUser.Size(m)
}
func (m *CEditUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CEditUser.DiscardUnknown(m)
}

var xxx_messageInfo_CEditUser proto.InternalMessageInfo

func (m *CEditUser) GetChangemask() uint32 {
	if m != nil {
		return m.Changemask
	}
	return 0
}

func (m *CEditUser) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CEditUser) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *CEditUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CEditUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CDelta struct {
	Revision             uint32   `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Ops                  []*Op    `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDelta) Reset()         { *m = CDelta{} }
func (m *CDelta) String() string { return proto.CompactTextString(m) }
func (*CDelta) ProtoMessage()    {}
func (*CDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{14}
}

func (m *CDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDelta.Unmarshal(m, b)
}
func (m *CDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDelta.Marshal(b, m, deterministic)
}
func (m *CDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDelta.Merge(m, src)
}
func (m *CDelta) XXX_Size() int {
	return xxx_messageInfo_CDelta.Size(m)
}
func (m *CDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_CDelta.DiscardUnknown(m)
}

var xxx_messageInfo_CDelta proto.InternalMessageInfo

func (m *CDelta) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *CDelta) GetOps() []*Op {
	if m != nil {
		return m.Ops
	}
	return nil
}

type CChat struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CChat) Reset()         { *m = CChat{} }
func (m *CChat) String() string { return proto.CompactTextString(m) }
func (*CChat) ProtoMessage()    {}
func (*CChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{15}
}

func (m *CChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CChat.Unmarshal(m, b)
}
func (m *CChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CChat.Marshal(b, m, deterministic)
}
func (m *CChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CChat.Merge(m, src)
}
func (m *CChat) XXX_Size() int {
	return xxx_messageInfo_CChat.Size(m)
}
func (m *CChat) XXX_DiscardUnknown() {
	xxx_messageInfo_CChat.DiscardUnknown(m)
}

var xxx_messageInfo_CChat proto.InternalMessageInfo

func (m *CChat) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type CSession struct {
	SessId               string   `protobuf:"bytes,1,opt,name=sessId,proto3" json:"sessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSession) Reset()         { *m = CSession{} }
func (m *CSession) String() string { return proto.CompactTextString(m) }
func (*CSession) ProtoMessage()    {}
func (*CSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{16}
}

func (m *CSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSession.Unmarshal(m, b)
}
func (m *CSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSession.Marshal(b, m, deterministic)
}
func (m *CSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSession.Merge(m, src)
}
func (m *CSession) XXX_Size() int {
	return xxx_messageInfo_CSession.Size(m)
}
func (m *CSession) XXX_DiscardUnknown() {
	xxx_messageInfo_CSession.DiscardUnknown(m)
}

var xxx_messageInfo_CSession proto.InternalMessageInfo

func (m *CSession) GetSessId() string {
	if m != nil {
		return m.SessId
	}
	return ""
}

type CLogin struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLogin) Reset()         { *m = CLogin{} }
func (m *CLogin) String() string { return proto.CompactTextString(m) }
func (*CLogin) ProtoMessage()    {}
func (*CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{17}
}

func (m *CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLogin.Unmarshal(m, b)
}
func (m *CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLogin.Marshal(b, m, deterministic)
}
func (m *CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLogin.Merge(m, src)
}
func (m *CLogin) XXX_Size() int {
	return xxx_messageInfo_CLogin.Size(m)
}
func (m *CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CLogin proto.InternalMessageInfo

func (m *CLogin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CLogout struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLogout) Reset()         { *m = CLogout{} }
func (m *CLogout) String() string { return proto.CompactTextString(m) }
func (*CLogout) ProtoMessage()    {}
func (*CLogout) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{18}
}

func (m *CLogout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLogout.Unmarshal(m, b)
}
func (m *CLogout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLogout.Marshal(b, m, deterministic)
}
func (m *CLogout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLogout.Merge(m, src)
}
func (m *CLogout) XXX_Size() int {
	return xxx_messageInfo_CLogout.Size(m)
}
func (m *CLogout) XXX_DiscardUnknown() {
	xxx_messageInfo_CLogout.DiscardUnknown(m)
}

var xxx_messageInfo_CLogout proto.InternalMessageInfo

type CRegister struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CRegister) Reset()         { *m = CRegister{} }
func (m *CRegister) String() string { return proto.CompactTextString(m) }
func (*CRegister) ProtoMessage()    {}
func (*CRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{19}
}

func (m *CRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CRegister.Unmarshal(m, b)
}
func (m *CRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CRegister.Marshal(b, m, deterministic)
}
func (m *CRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CRegister.Merge(m, src)
}
func (m *CRegister) XXX_Size() int {
	return xxx_messageInfo_CRegister.Size(m)
}
func (m *CRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_CRegister.DiscardUnknown(m)
}

var xxx_messageInfo_CRegister proto.InternalMessageInfo

func (m *CRegister) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CRegister) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type CGuestLogin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGuestLogin) Reset()         { *m = CGuestLogin{} }
func (m *CGuestLogin) String() string { return proto.CompactTextString(m) }
func (*CGuestLogin) ProtoMessage()    {}
func (*CGuestLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{20}
}

func (m *CGuestLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGuestLogin.Unmarshal(m, b)
}
func (m *CGuestLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGuestLogin.Marshal(b, m, deterministic)
}
func (m *CGuestLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGuestLogin.Merge(m, src)
}
func (m *CGuestLogin) XXX_Size() int {
	return xxx_messageInfo_CGuestLogin.Size(m)
}
func (m *CGuestLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CGuestLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CGuestLogin proto.InternalMessageInfo

type CEnterPad struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CEnterPad) Reset()         { *m = CEnterPad{} }
func (m *CEnterPad) String() string { return proto.CompactTextString(m) }
func (*CEnterPad) ProtoMessage()    {}
func (*CEnterPad) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{21}
}

func (m *CEnterPad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CEnterPad.Unmarshal(m, b)
}
func (m *CEnterPad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CEnterPad.Marshal(b, m, deterministic)
}
func (m *CEnterPad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CEnterPad.Merge(m, src)
}
func (m *CEnterPad) XXX_Size() int {
	return xxx_messageInfo_CEnterPad.Size(m)
}
func (m *CEnterPad) XXX_DiscardUnknown() {
	xxx_messageInfo_CEnterPad.DiscardUnknown(m)
}

var xxx_messageInfo_CEnterPad proto.InternalMessageInfo

func (m *CEnterPad) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CLeavePad struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLeavePad) Reset()         { *m = CLeavePad{} }
func (m *CLeavePad) String() string { return proto.CompactTextString(m) }
func (*CLeavePad) ProtoMessage()    {}
func (*CLeavePad) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{22}
}

func (m *CLeavePad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLeavePad.Unmarshal(m, b)
}
func (m *CLeavePad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLeavePad.Marshal(b, m, deterministic)
}
func (m *CLeavePad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLeavePad.Merge(m, src)
}
func (m *CLeavePad) XXX_Size() int {
	return xxx_messageInfo_CLeavePad.Size(m)
}
func (m *CLeavePad) XXX_DiscardUnknown() {
	xxx_messageInfo_CLeavePad.DiscardUnknown(m)
}

var xxx_messageInfo_CLeavePad proto.InternalMessageInfo

type CAdminUser struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Changemask           uint32   `protobuf:"varint,2,opt,name=changemask,proto3" json:"changemask,omitempty"`
	Perms                uint32   `protobuf:"varint,3,opt,name=perms,proto3" json:"perms,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color                uint32   `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CAdminUser) Reset()         { *m = CAdminUser{} }
func (m *CAdminUser) String() string { return proto.CompactTextString(m) }
func (*CAdminUser) ProtoMessage()    {}
func (*CAdminUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{23}
}

func (m *CAdminUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CAdminUser.Unmarshal(m, b)
}
func (m *CAdminUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CAdminUser.Marshal(b, m, deterministic)
}
func (m *CAdminUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CAdminUser.Merge(m, src)
}
func (m *CAdminUser) XXX_Size() int {
	return xxx_messageInfo_CAdminUser.Size(m)
}
func (m *CAdminUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CAdminUser.DiscardUnknown(m)
}

var xxx_messageInfo_CAdminUser proto.InternalMessageInfo

func (m *CAdminUser) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CAdminUser) GetChangemask() uint32 {
	if m != nil {
		return m.Changemask
	}
	return 0
}

func (m *CAdminUser) GetPerms() uint32 {
	if m != nil {
		return m.Perms
	}
	return 0
}

func (m *CAdminUser) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CAdminUser) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *CAdminUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CAdminUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CChatRequest struct {
	From                 uint32   `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CChatRequest) Reset()         { *m = CChatRequest{} }
func (m *CChatRequest) String() string { return proto.CompactTextString(m) }
func (*CChatRequest) ProtoMessage()    {}
func (*CChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{24}
}

func (m *CChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CChatRequest.Unmarshal(m, b)
}
func (m *CChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CChatRequest.Marshal(b, m, deterministic)
}
func (m *CChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CChatRequest.Merge(m, src)
}
func (m *CChatRequest) XXX_Size() int {
	return xxx_messageInfo_CChatRequest.Size(m)
}
func (m *CChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CChatRequest proto.InternalMessageInfo

func (m *CChatRequest) GetFrom() uint32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *CChatRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CRevisionRequest struct {
	Revision             uint32   `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CRevisionRequest) Reset()         { *m = CRevisionRequest{} }
func (m *CRevisionRequest) String() string { return proto.CompactTextString(m) }
func (*CRevisionRequest) ProtoMessage()    {}
func (*CRevisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{25}
}

func (m *CRevisionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CRevisionRequest.Unmarshal(m, b)
}
func (m *CRevisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CRevisionRequest.Marshal(b, m, deterministic)
}
func (m *CRevisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CRevisionRequest.Merge(m, src)
}
func (m *CRevisionRequest) XXX_Size() int {
	return xxx_messageInfo_CRevisionRequest.Size(m)
}
func (m *CRevisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CRevisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CRevisionRequest proto.InternalMessageInfo

func (m *CRevisionRequest) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

type CInvertDelta struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CInvertDelta) Reset()         { *m = CInvertDelta{} }
func (m *CInvertDelta) String() string { return proto.CompactTextString(m) }
func (*CInvertDelta) ProtoMessage()    {}
func (*CInvertDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{26}
}

func (m *CInvertDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CInvertDelta.Unmarshal(m, b)
}
func (m *CInvertDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CInvertDelta.Marshal(b, m, deterministic)
}
func (m *CInvertDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CInvertDelta.Merge(m, src)
}
func (m *CInvertDelta) XXX_Size() int {
	return xxx_messageInfo_CInvertDelta.Size(m)
}
func (m *CInvertDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_CInvertDelta.DiscardUnknown(m)
}

var xxx_messageInfo_CInvertDelta proto.InternalMessageInfo

func (m *CInvertDelta) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CInvertUserDelta struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CInvertUserDelta) Reset()         { *m = CInvertUserDelta{} }
func (m *CInvertUserDelta) String() string { return proto.CompactTextString(m) }
func (*CInvertUserDelta) ProtoMessage()    {}
func (*CInvertUserDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{27}
}

func (m *CInvertUserDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CInvertUserDelta.Unmarshal(m, b)
}
func (m *CInvertUserDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CInvertUserDelta.Marshal(b, m, deterministic)
}
func (m *CInvertUserDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CInvertUserDelta.Merge(m, src)
}
func (m *CInvertUserDelta) XXX_Size() int {
	return xxx_messageInfo_CInvertUserDelta.Size(m)
}
func (m *CInvertUserDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_CInvertUserDelta.DiscardUnknown(m)
}

var xxx_messageInfo_CInvertUserDelta proto.InternalMessageInfo

func (m *CInvertUserDelta) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CRestoreRevision struct {
	Rev                  uint32   `protobuf:"varint,1,opt,name=rev,proto3" json:"rev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CRestoreRevision) Reset()         { *m = CRestoreRevision{} }
func (m *CRestoreRevision) String() string { return proto.CompactTextString(m) }
func (*CRestoreRevision) ProtoMessage()    {}
func (*CRestoreRevision) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{28}
}

func (m *CRestoreRevision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CRestoreRevision.Unmarshal(m, b)
}
func (m *CRestoreRevision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CRestoreRevision.Marshal(b, m, deterministic)
}
func (m *CRestoreRevision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CRestoreRevision.Merge(m, src)
}
func (m *CRestoreRevision) XXX_Size() int {
	return xxx_messageInfo_CRestoreRevision.Size(m)
}
func (m *CRestoreRevision) XXX_DiscardUnknown() {
	xxx_messageInfo_CRestoreRevision.DiscardUnknown(m)
}

var xxx_messageInfo_CRestoreRevision proto.InternalMessageInfo

func (m *CRestoreRevision) GetRev() uint32 {
	if m != nil {
		return m.Rev
	}
	return 0
}

type Op struct {
	// Types that are valid to be assigned to Op:
	//	*Op_Insert
	//	*Op_Delete
	//	*Op_Retain
	Op                   isOp_Op  `protobuf_oneof:"op"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Op) Reset()         { *m = Op{} }
func (m *Op) String() string { return proto.CompactTextString(m) }
func (*Op) ProtoMessage()    {}
func (*Op) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{29}
}

func (m *Op) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Op.Unmarshal(m, b)
}
func (m *Op) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Op.Marshal(b, m, deterministic)
}
func (m *Op) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Op.Merge(m, src)
}
func (m *Op) XXX_Size() int {
	return xxx_messageInfo_Op.Size(m)
}
func (m *Op) XXX_DiscardUnknown() {
	xxx_messageInfo_Op.DiscardUnknown(m)
}

var xxx_messageInfo_Op proto.InternalMessageInfo

type isOp_Op interface {
	isOp_Op()
}

type Op_Insert struct {
	Insert *OpInsert `protobuf:"bytes,1,opt,name=insert,proto3,oneof"`
}

type Op_Delete struct {
	Delete *OpDelete `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type Op_Retain struct {
	Retain *OpRetain `protobuf:"bytes,3,opt,name=retain,proto3,oneof"`
}

func (*Op_Insert) isOp_Op() {}

func (*Op_Delete) isOp_Op() {}

func (*Op_Retain) isOp_Op() {}

func (m *Op) GetOp() isOp_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *Op) GetInsert() *OpInsert {
	if x, ok := m.GetOp().(*Op_Insert); ok {
		return x.Insert
	}
	return nil
}

func (m *Op) GetDelete() *OpDelete {
	if x, ok := m.GetOp().(*Op_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *Op) GetRetain() *OpRetain {
	if x, ok := m.GetOp().(*Op_Retain); ok {
		return x.Retain
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Op) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Op_Insert)(nil),
		(*Op_Delete)(nil),
		(*Op_Retain)(nil),
	}
}

type OpInsert struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Meta                 *OpMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpInsert) Reset()         { *m = OpInsert{} }
func (m *OpInsert) String() string { return proto.CompactTextString(m) }
func (*OpInsert) ProtoMessage()    {}
func (*OpInsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{30}
}

func (m *OpInsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpInsert.Unmarshal(m, b)
}
func (m *OpInsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpInsert.Marshal(b, m, deterministic)
}
func (m *OpInsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpInsert.Merge(m, src)
}
func (m *OpInsert) XXX_Size() int {
	return xxx_messageInfo_OpInsert.Size(m)
}
func (m *OpInsert) XXX_DiscardUnknown() {
	xxx_messageInfo_OpInsert.DiscardUnknown(m)
}

var xxx_messageInfo_OpInsert proto.InternalMessageInfo

func (m *OpInsert) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *OpInsert) GetMeta() *OpMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type OpDelete struct {
	Len                  uint32   `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpDelete) Reset()         { *m = OpDelete{} }
func (m *OpDelete) String() string { return proto.CompactTextString(m) }
func (*OpDelete) ProtoMessage()    {}
func (*OpDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{31}
}

func (m *OpDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpDelete.Unmarshal(m, b)
}
func (m *OpDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpDelete.Marshal(b, m, deterministic)
}
func (m *OpDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpDelete.Merge(m, src)
}
func (m *OpDelete) XXX_Size() int {
	return xxx_messageInfo_OpDelete.Size(m)
}
func (m *OpDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_OpDelete.DiscardUnknown(m)
}

var xxx_messageInfo_OpDelete proto.InternalMessageInfo

func (m *OpDelete) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type OpRetain struct {
	Len                  uint32   `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	Meta                 *OpMeta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpRetain) Reset()         { *m = OpRetain{} }
func (m *OpRetain) String() string { return proto.CompactTextString(m) }
func (*OpRetain) ProtoMessage()    {}
func (*OpRetain) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{32}
}

func (m *OpRetain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpRetain.Unmarshal(m, b)
}
func (m *OpRetain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpRetain.Marshal(b, m, deterministic)
}
func (m *OpRetain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpRetain.Merge(m, src)
}
func (m *OpRetain) XXX_Size() int {
	return xxx_messageInfo_OpRetain.Size(m)
}
func (m *OpRetain) XXX_DiscardUnknown() {
	xxx_messageInfo_OpRetain.DiscardUnknown(m)
}

var xxx_messageInfo_OpRetain proto.InternalMessageInfo

func (m *OpRetain) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *OpRetain) GetMeta() *OpMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type OpMeta struct {
	Changemask           uint32   `protobuf:"varint,1,opt,name=changemask,proto3" json:"changemask,omitempty"`
	Bold                 bool     `protobuf:"varint,2,opt,name=bold,proto3" json:"bold,omitempty"`
	Italic               bool     `protobuf:"varint,3,opt,name=italic,proto3" json:"italic,omitempty"`
	Underline            bool     `protobuf:"varint,4,opt,name=underline,proto3" json:"underline,omitempty"`
	Strike               bool     `protobuf:"varint,5,opt,name=strike,proto3" json:"strike,omitempty"`
	FontSize             uint32   `protobuf:"varint,6,opt,name=fontSize,proto3" json:"fontSize,omitempty"`
	UserId               uint32   `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpMeta) Reset()         { *m = OpMeta{} }
func (m *OpMeta) String() string { return proto.CompactTextString(m) }
func (*OpMeta) ProtoMessage()    {}
func (*OpMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f63176b85ff4e, []int{33}
}

func (m *OpMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpMeta.Unmarshal(m, b)
}
func (m *OpMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpMeta.Marshal(b, m, deterministic)
}
func (m *OpMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpMeta.Merge(m, src)
}
func (m *OpMeta) XXX_Size() int {
	return xxx_messageInfo_OpMeta.Size(m)
}
func (m *OpMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_OpMeta.DiscardUnknown(m)
}

var xxx_messageInfo_OpMeta proto.InternalMessageInfo

func (m *OpMeta) GetChangemask() uint32 {
	if m != nil {
		return m.Changemask
	}
	return 0
}

func (m *OpMeta) GetBold() bool {
	if m != nil {
		return m.Bold
	}
	return false
}

func (m *OpMeta) GetItalic() bool {
	if m != nil {
		return m.Italic
	}
	return false
}

func (m *OpMeta) GetUnderline() bool {
	if m != nil {
		return m.Underline
	}
	return false
}

func (m *OpMeta) GetStrike() bool {
	if m != nil {
		return m.Strike
	}
	return false
}

func (m *OpMeta) GetFontSize() uint32 {
	if m != nil {
		return m.FontSize
	}
	return 0
}

func (m *OpMeta) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*SMessages)(nil), "proto.SMessages")
	proto.RegisterType((*SMessage)(nil), "proto.SMessage")
	proto.RegisterType((*SChat)(nil), "proto.SChat")
	proto.RegisterType((*SDelta)(nil), "proto.SDelta")
	proto.RegisterType((*SDeltaDropped)(nil), "proto.SDeltaDropped")
	proto.RegisterType((*SDocument)(nil), "proto.SDocument")
	proto.RegisterType((*SAuth)(nil), "proto.SAuth")
	proto.RegisterType((*SAuthError)(nil), "proto.SAuthError")
	proto.RegisterType((*SUserLeave)(nil), "proto.SUserLeave")
	proto.RegisterType((*SUserInfo)(nil), "proto.SUserInfo")
	proto.RegisterType((*SPadList)(nil), "proto.SPadList")
	proto.RegisterType((*CMessages)(nil), "proto.CMessages")
	proto.RegisterType((*CMessage)(nil), "proto.CMessage")
	proto.RegisterType((*CEditUser)(nil), "proto.CEditUser")
	proto.RegisterType((*CDelta)(nil), "proto.CDelta")
	proto.RegisterType((*CChat)(nil), "proto.CChat")
	proto.RegisterType((*CSession)(nil), "proto.CSession")
	proto.RegisterType((*CLogin)(nil), "proto.CLogin")
	proto.RegisterType((*CLogout)(nil), "proto.CLogout")
	proto.RegisterType((*CRegister)(nil), "proto.CRegister")
	proto.RegisterType((*CGuestLogin)(nil), "proto.CGuestLogin")
	proto.RegisterType((*CEnterPad)(nil), "proto.CEnterPad")
	proto.RegisterType((*CLeavePad)(nil), "proto.CLeavePad")
	proto.RegisterType((*CAdminUser)(nil), "proto.CAdminUser")
	proto.RegisterType((*CChatRequest)(nil), "proto.CChatRequest")
	proto.RegisterType((*CRevisionRequest)(nil), "proto.CRevisionRequest")
	proto.RegisterType((*CInvertDelta)(nil), "proto.CInvertDelta")
	proto.RegisterType((*CInvertUserDelta)(nil), "proto.CInvertUserDelta")
	proto.RegisterType((*CRestoreRevision)(nil), "proto.CRestoreRevision")
	proto.RegisterType((*Op)(nil), "proto.Op")
	proto.RegisterType((*OpInsert)(nil), "proto.OpInsert")
	proto.RegisterType((*OpDelete)(nil), "proto.OpDelete")
	proto.RegisterType((*OpRetain)(nil), "proto.OpRetain")
	proto.RegisterType((*OpMeta)(nil), "proto.OpMeta")
}

func init() { proto.RegisterFile("esterpad.proto", fileDescriptor_de4f63176b85ff4e) }

var fileDescriptor_de4f63176b85ff4e = []byte{
	// 1207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5f, 0x6f, 0xdc, 0x44,
	0x10, 0x3f, 0xdf, 0x5f, 0x7b, 0x2e, 0x97, 0x84, 0xa5, 0x02, 0xab, 0xad, 0xda, 0xb2, 0x2a, 0x52,
	0xa1, 0x28, 0x12, 0x05, 0x09, 0xd4, 0x17, 0x94, 0x5e, 0x2a, 0x2e, 0x52, 0xa2, 0x54, 0x1b, 0xf1,
	0xc0, 0xa3, 0x7b, 0xde, 0x5c, 0xac, 0xdc, 0xd9, 0xc6, 0xde, 0x0b, 0x88, 0x17, 0x3e, 0x00, 0x0f,
	0x7c, 0x16, 0x24, 0x9e, 0xfb, 0xce, 0xb7, 0x42, 0x33, 0xfb, 0xc7, 0xde, 0x4b, 0xae, 0x94, 0x3e,
	0xf0, 0xe4, 0x9d, 0x99, 0xdf, 0xee, 0xcc, 0xec, 0xcc, 0xfc, 0xd6, 0xb0, 0x2b, 0x6b, 0x25, 0xab,
	0x32, 0x49, 0x0f, 0xca, 0xaa, 0x50, 0x05, 0x1b, 0xd0, 0x87, 0x7f, 0x01, 0xd1, 0xf9, 0xa9, 0xac,
	0xeb, 0x64, 0x21, 0x6b, 0xf6, 0x10, 0xba, 0xf5, 0x2a, 0x0e, 0x1e, 0xf5, 0x9e, 0x8c, 0x9f, 0xed,
	0x69, 0xdc, 0x81, 0xb5, 0x8a, 0x6e, 0xbd, 0xe2, 0x7f, 0xf5, 0x20, 0xb4, 0x0a, 0xc6, 0xa1, 0x3f,
	0xbd, 0x4c, 0x54, 0x1c, 0x3c, 0x0a, 0x9e, 0x8c, 0x9f, 0xed, 0x58, 0x3c, 0xea, 0x66, 0x1d, 0x41,
	0x36, 0xf6, 0x29, 0x0c, 0x8e, 0xe4, 0x52, 0x25, 0x71, 0x97, 0x40, 0x13, 0x0b, 0x22, 0xe5, 0xac,
	0x23, 0xb4, 0x95, 0x3d, 0x87, 0x1d, 0x5a, 0x1c, 0x55, 0x45, 0x59, 0xca, 0x34, 0xee, 0x11, 0xfa,
	0x8e, 0x87, 0x36, 0xb6, 0x59, 0x47, 0x78, 0x58, 0x76, 0x00, 0xe1, 0x51, 0x31, 0x5f, 0xaf, 0x64,
	0xae, 0xe2, 0x3e, 0xed, 0xdb, 0x77, 0xfb, 0x8c, 0x7e, 0xd6, 0x11, 0x0e, 0x83, 0x61, 0x1f, 0xae,
	0xd5, 0x65, 0x3c, 0xf0, 0xc3, 0x46, 0x1d, 0x86, 0x8d, 0x5f, 0xf6, 0x25, 0x44, 0xf8, 0x7d, 0x59,
	0x55, 0x45, 0x15, 0x0f, 0x09, 0xf8, 0x41, 0x1b, 0x48, 0x86, 0x59, 0x47, 0x34, 0x28, 0xdc, 0xf2,
	0x43, 0x2d, 0xab, 0x13, 0x99, 0x5c, 0xcb, 0x78, 0xe4, 0x6f, 0x71, 0x06, 0xdc, 0xe2, 0x04, 0x8c,
	0x1c, 0x85, 0xe3, 0xfc, 0xa2, 0x88, 0x43, 0x3f, 0x72, 0xab, 0xc7, 0xc8, 0xed, 0x9a, 0x3d, 0x85,
	0xd1, 0xab, 0x24, 0x3d, 0xc9, 0x6a, 0x15, 0x47, 0x04, 0x77, 0x35, 0x32, 0xea, 0x59, 0x47, 0x58,
	0xc4, 0x0b, 0x68, 0x2a, 0xc5, 0xa7, 0x30, 0xa0, 0xb2, 0xb0, 0x5d, 0xe8, 0x66, 0x29, 0x15, 0x6c,
	0x22, 0xba, 0x59, 0xca, 0x3e, 0x82, 0xe1, 0x1a, 0x4f, 0x4f, 0xa9, 0x3e, 0x13, 0x61, 0x24, 0xc6,
	0xa0, 0xaf, 0xe4, 0x2f, 0x8a, 0xea, 0x10, 0x09, 0x5a, 0xf3, 0x53, 0x18, 0xea, 0x42, 0xbc, 0xf3,
	0x29, 0xf7, 0xa0, 0x57, 0x94, 0x75, 0xdc, 0xa3, 0x7e, 0x8a, 0x4c, 0xac, 0x67, 0xa5, 0x40, 0x2d,
	0x7f, 0x0a, 0x13, 0xaf, 0xae, 0xec, 0x2e, 0x84, 0x95, 0xbc, 0xce, 0xea, 0xac, 0xc8, 0xcd, 0xd9,
	0x4e, 0xe6, 0x47, 0x10, 0xb9, 0x62, 0xbe, 0x0d, 0x68, 0x5d, 0x76, 0x6f, 0x75, 0xf9, 0x1b, 0x0c,
	0xa8, 0x7a, 0xad, 0x80, 0x03, 0x2f, 0xe0, 0xbb, 0x10, 0xe6, 0xd9, 0xfc, 0x2a, 0x4f, 0x56, 0x92,
	0x52, 0x89, 0x84, 0x93, 0xd9, 0x1d, 0x18, 0xcc, 0x8b, 0x65, 0x51, 0xd1, 0x9d, 0x4c, 0x84, 0x16,
	0x50, 0x5b, 0xca, 0x6a, 0x55, 0x53, 0xe7, 0x4d, 0x84, 0x16, 0xf0, 0xfc, 0x5a, 0xd6, 0xf5, 0x71,
	0x4a, 0x4d, 0x16, 0x09, 0x23, 0x71, 0x0e, 0xd0, 0xb4, 0x0f, 0xee, 0x95, 0xd4, 0x60, 0x3a, 0x08,
	0x2d, 0xf0, 0xc7, 0x00, 0x4d, 0xbf, 0x6c, 0x8b, 0x94, 0xff, 0x19, 0x40, 0xe4, 0x9a, 0xe4, 0xff,
	0xc8, 0xa7, 0xc8, 0x97, 0x59, 0x2e, 0x29, 0x9f, 0x50, 0x18, 0x89, 0x1a, 0xa1, 0xa4, 0xf9, 0x88,
	0x44, 0x37, 0x2b, 0xd9, 0x7d, 0x88, 0xd0, 0xf3, 0xe1, 0x02, 0x67, 0x71, 0x44, 0xea, 0x46, 0xc1,
	0x1f, 0x40, 0x68, 0x1b, 0x15, 0x1b, 0xac, 0x4c, 0xd2, 0x9a, 0xb8, 0x26, 0x12, 0xb4, 0x46, 0x2a,
	0x9a, 0xb6, 0xa9, 0x68, 0xbe, 0x49, 0x45, 0x53, 0x47, 0x45, 0xf3, 0x15, 0xff, 0x7b, 0x08, 0xa1,
	0x55, 0xe0, 0x24, 0xbd, 0x4c, 0x33, 0x85, 0x17, 0x62, 0xe8, 0xc8, 0x4e, 0xd2, 0xd4, 0xea, 0x71,
	0x92, 0xec, 0x7a, 0x1b, 0x2d, 0x4d, 0x37, 0x68, 0xc9, 0x32, 0x5c, 0xcf, 0xa3, 0x8a, 0xa9, 0xc7,
	0x70, 0x4f, 0x61, 0x74, 0x2e, 0x6b, 0x6a, 0xc6, 0xbe, 0x37, 0x94, 0x53, 0xa3, 0xc6, 0xa1, 0x34,
	0x4b, 0xf4, 0x7b, 0x52, 0x2c, 0xb2, 0xdc, 0x90, 0x8f, 0xf3, 0x4b, 0x4a, 0xf4, 0x4b, 0x0b, 0xf6,
	0x04, 0x86, 0x27, 0xc5, 0xa2, 0x58, 0x2b, 0xc3, 0x3d, 0xbb, 0x2d, 0x5c, 0xb1, 0x46, 0xdf, 0xc6,
	0x8e, 0x89, 0x0b, 0xb9, 0xc8, 0x90, 0xda, 0x0d, 0xe9, 0xb8, 0xc4, 0xad, 0x1e, 0x13, 0xb7, 0x6b,
	0xf6, 0x35, 0xc0, 0xf7, 0x6b, 0x59, 0x2b, 0x1d, 0x85, 0x26, 0x1d, 0x66, 0x77, 0x34, 0x96, 0x59,
	0x47, 0xb4, 0x70, 0x74, 0xbd, 0xb9, 0x92, 0xd5, 0xab, 0x24, 0x35, 0xcc, 0xd3, 0x5c, 0xaf, 0xd1,
	0xd3, 0xf5, 0x9a, 0x35, 0xe2, 0xa9, 0x7d, 0x11, 0x0f, 0x3e, 0xde, 0xea, 0x11, 0x6f, 0xd7, 0x44,
	0xb7, 0xe9, 0x2a, 0xcb, 0xa9, 0x7e, 0x63, 0x8f, 0x3b, 0xa7, 0xce, 0x40, 0x74, 0x6b, 0x05, 0xf6,
	0x0d, 0x8c, 0xf1, 0xfa, 0x85, 0xfc, 0x09, 0xc3, 0x8c, 0x77, 0x68, 0xd3, 0x87, 0xed, 0x0a, 0x19,
	0xd3, 0xac, 0x23, 0xda, 0x48, 0x36, 0x85, 0x3d, 0x61, 0xd8, 0xc2, 0x6e, 0x9e, 0xd0, 0xe6, 0x8f,
	0x9b, 0x8b, 0xf3, 0xcc, 0xb3, 0x8e, 0xd8, 0xdc, 0x81, 0xde, 0x8f, 0xf3, 0x6b, 0x59, 0x29, 0xdd,
	0x45, 0xbb, 0xbe, 0xf7, 0x96, 0x09, 0xbd, 0xb7, 0x44, 0xf4, 0xae, 0x45, 0x4c, 0x42, 0x6f, 0xde,
	0xf3, 0xbd, 0x6f, 0x98, 0xd1, 0xfb, 0x86, 0x4a, 0xa7, 0x50, 0xab, 0xa2, 0x92, 0x36, 0xae, 0x78,
	0x7f, 0x33, 0x05, 0xcf, 0xac, 0x53, 0xf0, 0x54, 0xf8, 0x3e, 0xd8, 0xf1, 0xe1, 0x7f, 0x04, 0x10,
	0xb9, 0x41, 0x61, 0x0f, 0x00, 0xe6, 0x97, 0x49, 0xbe, 0x90, 0xab, 0xa4, 0xbe, 0x32, 0x8c, 0xd2,
	0xd2, 0xbc, 0x1f, 0xab, 0xc8, 0x55, 0x92, 0x2d, 0x69, 0x42, 0x22, 0xa1, 0x05, 0x3c, 0xa7, 0x4c,
	0xea, 0xfa, 0xe7, 0xa2, 0xb2, 0x3c, 0xe9, 0x64, 0x7e, 0x08, 0x43, 0x3d, 0x8c, 0xef, 0xcf, 0xf6,
	0xf7, 0x60, 0x40, 0x7d, 0xe0, 0x1e, 0xb3, 0xa0, 0xf5, 0x98, 0x71, 0x08, 0xed, 0x7c, 0xb6, 0xd8,
	0x3a, 0xf0, 0xd8, 0xfa, 0x39, 0x0c, 0xf5, 0x60, 0x36, 0xf1, 0x07, 0xdb, 0xe2, 0xef, 0x6e, 0xc4,
	0x1f, 0xc1, 0xc8, 0x0c, 0x2b, 0xff, 0x11, 0x22, 0x37, 0x8b, 0xff, 0xfd, 0x24, 0xef, 0xb6, 0x7b,
	0xfe, 0x6d, 0xf3, 0x09, 0x8c, 0x5b, 0x43, 0xcb, 0x1f, 0x62, 0x15, 0xed, 0x0c, 0x32, 0xe8, 0xd3,
	0x1e, 0x93, 0x35, 0xe1, 0xc7, 0x10, 0xb9, 0x01, 0xe4, 0x6f, 0x02, 0x80, 0x66, 0xba, 0xb6, 0xbe,
	0x21, 0x7e, 0x37, 0x74, 0x6f, 0x74, 0x83, 0x7b, 0x31, 0x7a, 0xed, 0x17, 0xa3, 0x1d, 0x75, 0x7f,
	0x5b, 0x8f, 0x0c, 0x6e, 0xed, 0x91, 0xe1, 0xb6, 0x9b, 0x19, 0x6d, 0xdc, 0xf1, 0xb7, 0xb0, 0xd3,
	0x1e, 0x74, 0xcc, 0xf8, 0xa2, 0x2a, 0x56, 0x26, 0x7e, 0x5a, 0x6b, 0x5f, 0xeb, 0x5c, 0x99, 0xc0,
	0xb5, 0xc0, 0x0f, 0x60, 0x7f, 0x73, 0xca, 0xdf, 0xfa, 0xfb, 0xf1, 0x00, 0x76, 0xda, 0x43, 0xbd,
	0xf9, 0x03, 0xc4, 0x3f, 0x87, 0xfd, 0xcd, 0xb9, 0xdd, 0xfa, 0x72, 0x3f, 0x26, 0xdf, 0xde, 0x2c,
	0xb2, 0x7d, 0xe8, 0x55, 0xf2, 0xda, 0x00, 0x71, 0xc9, 0x7f, 0x0f, 0xa0, 0x7b, 0x56, 0xb2, 0xcf,
	0x60, 0x98, 0xe5, 0xb5, 0xac, 0xec, 0x4f, 0xf6, 0x9e, 0xeb, 0xf1, 0x63, 0x52, 0xe3, 0x4b, 0xa0,
	0x01, 0x08, 0x4d, 0xe5, 0x52, 0x2a, 0x69, 0xde, 0xb4, 0x06, 0x7a, 0x44, 0x6a, 0x84, 0x6a, 0x00,
	0x42, 0x2b, 0xa9, 0x92, 0x2c, 0x37, 0x0f, 0x5b, 0x03, 0x15, 0xa4, 0x46, 0xa8, 0x06, 0xbc, 0xe8,
	0x43, 0xb7, 0x28, 0xf9, 0x21, 0x84, 0xd6, 0xe3, 0x6d, 0xd3, 0xc4, 0x3e, 0x81, 0xfe, 0x4a, 0xde,
	0x78, 0x4d, 0xcf, 0xca, 0x53, 0xa9, 0x12, 0x41, 0x26, 0x7e, 0x1f, 0x8f, 0xd0, 0x91, 0x60, 0xba,
	0x4b, 0x69, 0x6f, 0x19, 0x97, 0xfc, 0x3b, 0xb4, 0x6a, 0xe7, 0x37, 0xad, 0xef, 0x72, 0xfc, 0x9b,
	0x00, 0x86, 0x5a, 0xf1, 0xaf, 0xf4, 0xc5, 0xa0, 0xff, 0xba, 0x58, 0xea, 0x41, 0x0b, 0x05, 0xad,
	0xb1, 0x58, 0x99, 0x4a, 0x96, 0xd9, 0x9c, 0x6e, 0x24, 0x14, 0x46, 0xa2, 0x1f, 0x9a, 0x3c, 0x95,
	0x15, 0xfd, 0xfb, 0xf4, 0xc9, 0xd4, 0x28, 0x88, 0x38, 0x54, 0x95, 0x5d, 0xb9, 0xdf, 0x22, 0x2d,
	0x61, 0x2b, 0x5d, 0x14, 0xb9, 0x3a, 0xcf, 0x7e, 0x95, 0xd4, 0xcd, 0x13, 0xe1, 0xe4, 0x56, 0x5b,
	0x8c, 0xda, 0x6d, 0xf1, 0x7a, 0x48, 0x49, 0x7d, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c,
	0xec, 0xf2, 0x34, 0xa7, 0x0d, 0x00, 0x00,
}
